# Render.yaml configuration for AI Trading Assistant
services:
  - type: web
    name: ai-trading-assistant
    env: python
    buildCommand: |
      pip install numpy && \
      pip install -r requirements.txt && \
      pip install --no-binary :all: git+https://github.com/mrjbq7/ta-lib.git@master
    startCommand: gunicorn dashboard.app_with_auth:server
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
